### ISSUE TITLE
Issue in Class-based L2 processing: 6S model not found

### ISSUE THREAD

**Issue by kristalikas** [nasa/HyperCP#256]
![Screenshot 2024-10-15 at 13 59 02](https://github.com/user-attachments/assets/1f0d20c8-9a2a-4153-bada-6a7090c5b7b6)

![image](https://github.com/user-attachments/assets/3629c584-519b-4dbf-be56-8c31c4710dd3)

**Comment by oceancolorcoder** [comment]
@kristalikas, this may be because you are running on an older L1BQC file that did not save the 6S model after use. Did you try reprocessing from L0 (or L1AQC)?

**Comment by ARamsay17** [comment]
@kristalikas I have had the same issue when running the TriOS sample data. It was solved by rebuilding my conda environment using the environment.yml file provided in the HyperCP repository. In addition I have found uninstalling py6s and reinstalling with conda-forge (version 1.9.2) has helped resolve this issue in the past. I hope this is useful.

**Comment by kristalikas** [comment]
@oceancolorcoder I have tried the reprocessing both ways, 1) from L0 and also 2) single level processing. It still produces the same error message on L2 processing.

@ARamsay17 I tried rebuilding the conda environment, and also uninstalling py6s and reinstalling (version 1.9.2) with conda-forge. Still got the same error message.

**Comment by oceancolorcoder** [comment]
@kristalikas @ARamsay17 I had this error for the first time this week. In my case the following worked, though it is unclear the first step did anything:
With the hypercp environment active:

conda install py6s 

(still getting the error after complete)

Close and re-open VSCode

That seemed to fix it for some reason. Anyway, the py6s module will be going away fairly soon, so hopefully we won't need to chase this issue down, because it's a weird and sporadic thing that's very difficult to trace.

Closing the issue, but we can re-open if this continues to bug us.

**Comment by jutavora** [comment]
Currently facing a similar issue. No problems running the FICE sample data but when running my own TRIOS no tracker data I get a similar error message. I have tried the solution mentioned above but no luck.

**Comment by oceancolorcoder** [comment]
Hi @jutavora , 

Just back from a short break - sorry for the delay.

Please open a new issue (the 6S module is completely different now) and provide us a little background to help you. 1) HyperCP version and operating system, 2) what you try to do and what you expect should happen, 3) what actually happens and the error logs (if any) from your terminal.

Cheers,
Dirk

PS. Your direct email just came to light while digging out. I will respond presently.
