### ISSUE TITLE
Build and Application Test fail

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#339]
Updated master for the first time in 4 mos. and the builds ran into some kind of “maximum recursion depth exceeded” error: https://github.com/nasa/HyperCP/actions/runs/14272644946
 
The application tests also had some kind of problem with h5py: “ValueError: numpy.dtype size changed, may indicate binary incompatibility”
 
@doizuc

**Comment by doizuc** [comment]
I was able to reproduce the failing tests. It is related to an environment issue: an incompatibility between h5py 3.7 and numpy 2 (more info [here](https://github.com/h5py/h5py/issues/2420)). When I create the environment with conda or mamba despite having  `numpy=1.23`, my resulting environment has `numpy-2.2.4` installed with `hy5p-3.7`. Could you check your current environment and build a new one and let me know what you version you have for these two packages?

I tried updating hy5p in the environment file but conda didn't took it and I had to update it with `pip install --upgrade hy5p` once the environment was installed. That solved the issue for h5py but raised the next incompatible library `pandas=1.53` and kept cascading to other libraries... I know you spent a lot of time getting the environment to be stable and work. Do you have any tips? Should I update the entire environment?

**Comment by doizuc** [comment]
The issue comes from the latest version of `comet-math` which required `numpy>=2.2.4`. comet-math is a dependency of `punpy` which is installed via pip which overwrote version set for other dependencies in the `environment.yml`. Adding `comet_maths<=1.0.3` in the `environment.yml` file should solve the issue.

**Comment by doizuc** [comment]
@raphidoc on the Windows VM of GitHub performing the tests (Windows Server 2022), `j6s` cannot find the executable. See error below. It runs well on macOS and Ubuntu. Any ideas? 

```
======================================================================
ERROR: test_manual_trios (Tests.test_sample_data.TestManualTriOS.test_manual_trios)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\HyperCP\HyperCP\Tests\test_sample_data.py", line 21, in test_manual_trios
    Command(self.cfg_filename, 'RAW', self.files, self.path_to_data,'L1A',
  File "D:\a\HyperCP\HyperCP\Main.py", line 674, in __init__
    Controller.processFilesMultiLevel(
  File "D:\a\HyperCP\HyperCP\Source\Controller.py", line 856, in processFilesMultiLevel
    if Controller.processSingleLevel(pathOut, fp, calibrationMap, 'L1B'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\HyperCP\HyperCP\Source\Controller.py", line 641, in processSingleLevel
    root = Controller.processL1b(inFilePath, outFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\HyperCP\HyperCP\Source\Controller.py", line 386, in processL1b
    root = ProcessL1bTriOS.processL1b(root, outFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\HyperCP\HyperCP\Source\ProcessL1bTriOS.py", line 474, in processL1b
    if not ProcessL1bTriOS.processDarkCorrection_FRM(node, sensortype, stats):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\HyperCP\HyperCP\Source\ProcessL1bTriOS.py", line 78, in processDarkCorrection_FRM
    res_sixS = ProcessL1b_FRMCal.get_direct_irradiance_ratio(node, sensortype)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\HyperCP\HyperCP\Source\ProcessL1b_FRMCal.py", line 99, in get_direct_irradiance_ratio
    s = SixS()
        ^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\hypercp\Lib\site-packages\j6s\wrap.py", line 17, in __init__
    if not os.path.exists(self.sixs_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by oceancolorcoder** [comment]
@doizuc Nice sleuthing on the dependencies conflict. I will update the env file in dev.

**Comment by raphidoc** [comment]
@doizuc I'll try running the tests on my Windows machine to see if I can reproduce the error.

**Comment by oceancolorcoder** [comment]
Build successful. New release v1.2.12. Application testing pending.

**Comment by oceancolorcoder** [comment]
@doizuc @raphidoc 

Application testing hit a snag with 6S in Windows.
https://github.com/nasa/HyperCP/actions/runs/14365871735/job/40278519930

**Comment by raphidoc** [comment]
@doizuc @oceancolorcoder, I've found the culprit—my bad! The part of the code finding the `sixs_json` path doesn't consider that on Windows, the executable is actually `sixs_json.exe` (actually, I must have done that in development because some of the code finding `sixs_json.exe` was commented out).
I'll check how to properly find the executable on various platforms and submit a fix as soon as possible.

**Comment by doizuc** [comment]
Good to hear you have a fix @raphidoc, looking forward to testing it!

**Comment by raphidoc** [comment]
@doizuc @oceancolorcoder, the fix on j6s is out. The HyperCP test suite ran correctly on my Windows machine (just add to change the ECMWF to MERRA2 ancillary data; for some reason, my ECMWF credentials are not recognized/valid).

So, if you rerun the test on GitHub, it should work fine. We should also advise every Windows user to re-create their hypercp environment.

**Comment by oceancolorcoder** [comment]
Tried rerunning the action with the same result: https://github.com/nasa/HyperCP/actions/runs/14404237440/job/40416336950

**Comment by doizuc** [comment]
@oceancolorcoder delete windows cache under Actions > Management > Caches. You should see two caches one for the application build and one for the testing. Then re-run both Bundle and Testing. They should go through. The environment is cached and only updated if we update the environment.yml, given that the package j6s was fixed, our environment will be rebuilt with the latest fixed package.

**Comment by oceancolorcoder** [comment]
I only saw one cache tagged for windows. Didn't specify build or testing. I've deleted it and will retry.

**Comment by oceancolorcoder** [comment]
@raphidoc Application testing still fails for Windows running 6S.

**Comment by oceancolorcoder** [comment]
Even stranger, between Friday and today I am getting the same problem on MacOS:
macOS Sequoia 15.3.2
j6s 1.0.0

Inconsistent path-related  crash in j6s. Ran fine for several files on Friday but this morning seems to be unable to interpret self.sixs_path:

```
Running sixS
Traceback (most recent call last):
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 577, in multi2Clicked
    self.processMulti()
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 570, in processMulti
    Controller.processFilesMultiLevel(
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 856, in processFilesMultiLevel
    if Controller.processSingleLevel(pathOut, fp, calibrationMap, 'L1B'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 641, in processSingleLevel
    root = Controller.processL1b(inFilePath, outFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 388, in processL1b
    root = ProcessL1b.processL1b(root, outFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL1b.py", line 752, in processL1b
    ProcessL1b_FactoryCal.processL1b_SeaBird(node, calibrationMap)
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL1b_FactoryCal.py", line 271, in processL1b_SeaBird
    res_sixS = ProcessL1b_FRMCal.get_direct_irradiance_ratio(node, sensortype)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL1b_FRMCal.py", line 99, in get_direct_irradiance_ratio
    s = SixS()
        ^^^^^^
  File "/Users/daurin/miniforge3/envs/hypercp/lib/python3.11/site-packages/j6s/wrap.py", line 17, in __init__
    if not os.path.exists(self.sixs_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/miniforge3/envs/hypercp/lib/python3.11/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by oceancolorcoder** [comment]
Further testing on wrap.py:

```
>>> os.path.exists(os.path.join('/Users/daurin/miniforge3/envs/hypercp/bin','six_json'))
False
```

**Comment by oceancolorcoder** [comment]
Tested okay on linux after env update.

**Comment by oceancolorcoder** [comment]
Here's an odd thing. When I activate hypercp from terminal, then launch python, os.environ["PATH"] includes /Users/daurin/miniforge3/envs/hypercp/bin at the head of the path list. If I put a breakpoint in HyperCP (running in VSCode in hypercp environment), os.environ["PATH"] is completely different and does not include /Users/daurin/miniforge3/envs/hypercp/bin. When I run HyperCP in hypercp from the terminal, it finds the path to sixs_json and runs it without error.

**Comment by raphidoc** [comment]
Hello Dirk, the test still fails on Windows because the version of j6s in the environment is 1.0.0, when it should be 1.0.1.
This is because the environment is cached, as Nils pointed out. 

The application testing has used the cached environment: conda-Windows-X64-059ddcb923a2ec9115dc2862c5b657fce412273aee578b8046bc87b543f27287-1

What is strange is that this Windows cache was built three days ago, after I updated the version of j6s. I'm not sure why it didn't install j6s v1.0.1, but I've noticed some lag between the release of v1.0.1 on Conda Forge and the availability of that version when installed from Mamba. My guess is that the conda forge package registry is updated at regular intervals, and there might be a mirror of the archive depending on your location. 

This is the environment on nasa/HyperCP (line 394: the cache is found and restored with j6s v1.0.0): https://github.com/doizuc/HyperCP/actions/runs/14404920322/job/40418990808#step:3:408 

And this is the version on doizuc/HyperCP (line 394: the cache is not found and all package where re-downloaded and installed with j6s v1.0.1): https://github.com/doizuc/HyperCP/actions/runs/14404920322/job/40418990808#step:3:408

I would try to delete the Windows cache again and rerun the application testing :)
The test runs fine on Nils fork, so it should also work in NASA once the environment is updated with j6s v1.0.1.

**Comment by raphidoc** [comment]
> Here's an odd thing. When I activate hypercp from terminal, then launch python, os.environ["PATH"] includes /Users/daurin/miniforge3/envs/hypercp/bin at the head of the path list. If I put a breakpoint in HyperCP (running in VSCode in hypercp environment), os.environ["PATH"] is completely different and does not include /Users/daurin/miniforge3/envs/hypercp/bin. When I run HyperCP in hypercp from the terminal, it finds the path to sixs_json and runs it without error.

Yes, that is not surprising. When you activate the environment, it is added to your PATH, and when you run in debug mode in VSCode (or else), nobody knows what's happening ;). To deal with this kind of thing in j6s v1.0.1, I use `os.environ.get("CONDA_PREFIX")` to find the absolute path of the environment root from Python. To find an executable, `shutil.which("sixs_json")` is handy as a backup.

**Comment by oceancolorcoder** [comment]
Okay, but after updating to j6s 1.0.1 and restarting VSCode, I still get the related error:

```
File "/Users/daurin/miniforge3/envs/hypercp/lib/python3.11/site-packages/j6s/wrap.py", line 17, in __init__
    self.sixs_path = self._find_path(path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/miniforge3/envs/hypercp/lib/python3.11/site-packages/j6s/wrap.py", line 66, in _find_path
    raise FileNotFoundError(
FileNotFoundError: 6S executable 'sixs_json' not found in provided path, conda env, or system PATH.
```

**Comment by raphidoc** [comment]
@oceancolorcoder would you have time to meet so that I can debug that with you ?

**Comment by oceancolorcoder** [comment]
Pas aujourd'hui. Maybe mañana. Cheers

**Comment by oceancolorcoder** [comment]
@doizuc @raphidoc 
Application test for Windows passed after second deletion of cache. Leaving issue open until I can resolve path to sixs_json locally.

**Comment by raphidoc** [comment]
j6s v1.0.2 use sys.prefix instead of os.enviro["CONDA_PREFIX"]. The latter returned the base conda env, not the activated env, on debug mode in VSCode on MacOS. Similarly, the shutil.which(exe_name) fallback seems to fail in that case.

Fixes the issue. Wait a few hours before j6sv1.0.2 becomes available :)

**Comment by oceancolorcoder** [comment]
Excellent! Thank you, @raphidoc. Will close shortly.
